"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");

const index = fs.readFileSync("index.html", "utf8");
const firebaseConfig = fs.readFileSync("firebase-config.js", "utf8");
const app = fs.readFileSync("app.js", "utf8");
const full = fs.readFileSync("full-team-championships.js", "utf8");
const miniStore = fs.readFileSync("tournament-store.js", "utf8");

assert.match(index, /id="tournament-team-cards"/);
assert.match(index, /id="championship-team-cards"/);
assert.match(app, /function renderTournamentTeamCards/);
assert.match(full, /function renderTeamCards/);
assert.match(app, /View players/);
assert.match(full, /View players/);
assert.match(full, /headCoachId/);
assert.match(full, /staffIds/);
assert.doesNotMatch(miniStore, /headCoachId|staffIds/);
assert.doesNotMatch(app, /headCoachId|staffIds/);
const ratings = fs.readFileSync("player-ratings.js", "utf8");
assert.match(index, /data-view="ratings"/);
assert.match(index, /id="ratings-view"/);
assert.match(index, /player-ratings\.js/);
assert.match(app, /InazumaPlayerRatings\?\.render/);
assert.match(ratings, /globalThis\.INAZUMA_PLAYERS/);
assert.match(ratings, /globalThis\.INAZUMA_TEAMS/);
assert.doesNotMatch(ratings, /fetch\s*\(/);
assert.doesNotMatch(ratings, /import\s+.*from|export\s+\{|type="module"/);
assert.match(index, /firebase-app-compat\.js/);
assert.match(index, /firebase-firestore-compat\.js/);
assert.match(index, /firebase-auth-compat\.js/);
assert.match(index, /firebase-config\.js/);
assert.doesNotMatch(index, /type=["\']module["\']/);
assert.match(firebaseConfig, /INAZUMA_FIREBASE_READY/);
assert.match(firebaseConfig, /INAZUMA_FIRESTORE/);
assert.match(firebaseConfig, /INAZUMA_FIREBASE_AUTH/);
assert.doesNotMatch(firebaseConfig, /import\s+.*from|export\s+\{|analytics/i);

["attack", "physical", "stamina", "control", "defense", "speed", "grit", "save"].forEach((stat) => assert.match(ratings, new RegExp(`\"${stat}\"`)));
assert.match(ratings, /localStorage/);
assert.match(ratings, /inazumaRatingProjects/);
assert.match(ratings, /signInAnonymously/);
assert.match(ratings, /onSnapshot/);
assert.match(index, /Carica rating locali su Firestore/);
assert.match(index, /Importa ratings\.json/);
assert.match(index, /Nome valutatore/);
assert.match(index, /ratings-sync-panel/);
assert.match(index, /ratings-sync-count/);
assert.match(ratings, /auth\.currentUser/);
assert.match(ratings, /signInAnonymously\(\)/);
assert.match(ratings, /listenerActive/);
assert.match(ratings, /Firebase SDK non caricato/);
assert.match(ratings, /Permission denied: controlla le Rules/);
assert.match(index, /Export ratings\.json/);
assert.match(index, /Export teams\.rated\.json/);
assert.match(index, /<details class="ratings-debug-details">/);
assert.match(index, /ratings-toggle-teams/);
assert.match(ratings, /ratings\.json/);
assert.match(ratings, /teams\.rated\.json/);
assert.match(index, /Export per squadre/);
assert.match(index, /Export squadre selezionate/);
assert.match(ratings, /selected-teams-ratings\.json/);
assert.match(ratings, /exportSelectedTeamsRatingsJson/);
assert.match(ratings, /logoUrl: teamLogoUrl/);
assert.match(ratings, /portraitUrl: playerPortraitUrl/);
assert.match(ratings, /"crestUrl"/);
assert.match(ratings, /"pictureUrl"/);
assert.match(ratings, /element: playerElement/);
assert.match(ratings, /"attribute"/);
assert.match(ratings, /"elemento"/);
assert.match(ratings, /return "Albero"/);
assert.match(ratings, /return "Fuoco"/);
assert.match(ratings, /return "Montagna"/);
assert.match(ratings, /return "Vento"/);
assert.match(ratings, /SALVA E PROSSIMO/);

const weightsMatch = ratings.match(/const ROLE_WEIGHTS = (\{[\s\S]*?\n  \});/);
assert.ok(weightsMatch, "ROLE_WEIGHTS must be declared");
const ROLE_WEIGHTS = Function(`return (${weightsMatch[1]});`)();
assert.equal(ROLE_WEIGHTS.FW.attack, 50);
assert.equal(ROLE_WEIGHTS.MF.control, 40);
assert.equal(ROLE_WEIGHTS.DF.defense, 50);
assert.equal(ROLE_WEIGHTS.GK.save, 70);
Object.entries(ROLE_WEIGHTS).forEach(([role, weights]) => {
  assert.equal(Object.values(weights).reduce((sum, value) => sum + value, 0), 100, `${role} weights must sum to 100`);
});

console.log("UI contract tests passed.");
